export interface MasterRecord {
  [key: string]: any
}

export interface FieldSchema {
  key: string
  label: string
  type: string
  ui: string
  required?: boolean
  relation?: string
  options?: string[]
  optionsEndpoint?: string
  default?: string
}

export interface MasterSchema {
  [key: string]: FieldSchema[]
}

export const masterSchemas: MasterSchema = {
  company: [
    { key: "company_name", label: "Company Name", type: "string", ui: "text", required: false },
    { key: "short_name", label: "Short Name", type: "string", ui: "text", required: false },
    { key: "cin_no", label: "CIN No.", type: "string", ui: "text", required: false },
    { key: "gstin", label: "GSTIN", type: "string", ui: "text", required: false },
    { key: "pan_no", label: "PAN No.", type: "string", ui: "text", required: false },
    { key: "address_line1", label: "Address Line 1", type: "string", ui: "textarea", required: false },
    { key: "address_line2", label: "Address Line 2", type: "string", ui: "textarea", required: false },
    { key: "city", label: "City", type: "string", ui: "text", required: false },
    { key: "state", label: "State", type: "string", ui: "text", required: false },
    { key: "country", label: "Country", type: "string", ui: "text", required: false, default: "India" },
    { key: "pin_code", label: "Pin Code", type: "string", ui: "text", required: false },
    { key: "contact_number", label: "Contact Number", type: "string", ui: "text", required: false },
    { key: "email", label: "Email", type: "string", ui: "email", required: false },
    { key: "website", label: "Website", type: "string", ui: "url", required: false },
    { key: "financial_year_start", label: "Financial Year Start", type: "date", ui: "date", required: false },
    { key: "financial_year_end", label: "Financial Year End", type: "date", ui: "date", required: false },
    { key: "default_currency", label: "Default Currency", type: "string", ui: "select", relation: "currency", required: false },
    { key: "company_logo", label: "Company Logo", type: "file", ui: "image", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: false }
  ],
  branch: [
    { key: "branch_id", label: "Branch ID", type: "string", ui: "auto", required: false },
    { key: "branch_name", label: "Branch Name", type: "string", ui: "text", required: false },
    { key: "company", label: "Company", type: "string", ui: "select", relation: "company", required: false },
    { key: "address", label: "Address", type: "string", ui: "textarea", required: false },
    { key: "city", label: "City", type: "string", ui: "text", required: false },
    { key: "state", label: "State", type: "string", ui: "text", required: false },
    { key: "country", label: "Country", type: "string", ui: "text", default: "India", required: false },
    { key: "contact_person", label: "Contact Person", type: "string", ui: "text", required: false },
    { key: "contact_number", label: "Contact Number", type: "string", ui: "text", required: false },
    { key: "email", label: "Email", type: "string", ui: "email", required: false },
    { key: "type", label: "Type", type: "string", ui: "select", options: ["Manufacturing","Head Office","Warehouse"], required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: false }
  ],
  department: [
    { key: "department_id", label: "Department ID", type: "string", ui: "auto", required: false },
    { key: "department_name", label: "Department Name", type: "string", ui: "text", required: false },
    { key: "department_code", label: "Department Code", type: "string", ui: "text", required: false },
    { key: "company", label: "Company", type: "string", ui: "select", relation: "company", required: false },
    { key: "head_of_department", label: "Head of Department", type: "string", ui: "select", relation: "employee", required: false },
    { key: "parent_department", label: "Parent Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: false }
  ],
  user: [
    { key: "user_id", label: "User ID", type: "string", ui: "auto", required: false },
    { key: "full_name", label: "Full Name", type: "string", ui: "text", required: false },
    { key: "username", label: "Username", type: "string", ui: "text", required: false },
    { key: "password", label: "Password", type: "string", ui: "password", required: false },
    { key: "email", label: "Email", type: "string", ui: "email", required: false },
    { key: "mobile_number", label: "Mobile Number", type: "string", ui: "text", required: false },
    { key: "role", label: "Role", type: "string", ui: "select", relation: "role", required: false },
    { key: "department", label: "Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "branch", label: "Branch", type: "string", ui: "select", relation: "branch", required: false },
    { key: "employee_code", label: "Employee Code", type: "string", ui: "select", relation: "employee", required: false },
    { key: "access_level", label: "Access Level", type: "string", ui: "select", options: ["Admin","User","Viewer"], required: false },
    { key: "last_login", label: "Last Login", type: "string", ui: "datetime", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: false }
  ],
  role: [
    { key: "role_id", label: "Role ID", type: "string", ui: "auto", required: false },
    { key: "role_name", label: "Role Name", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "module_access", label: "Module Access", type: "string", ui: "multiselect", options: ["Production","Inventory","Quality","Purchase","Sales","HR","Finance"], required: false },
    { key: "permission_level", label: "Permission Level", type: "number", ui: "number", required: false },
    { key: "approval_authority", label: "Approval Authority", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: false }
  ],
  employee: [
    { key: "employee_id", label: "Employee ID", type: "string", ui: "auto", required: false },
    { key: "employee_code", label: "Employee Code", type: "string", ui: "text", required: false },
    { key: "employee_name", label: "Employee Name", type: "string", ui: "text", required: false },
    { key: "gender", label: "Gender", type: "string", ui: "select", options: ["M","F","Other"], required: false },
    { key: "date_of_birth", label: "Date of Birth", type: "date", ui: "date", required: false },
    { key: "date_of_joining", label: "Date of Joining", type: "date", ui: "date", required: false },
    { key: "department", label: "Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "designation", label: "Designation", type: "string", ui: "text", required: false },
    { key: "reporting_manager", label: "Reporting Manager", type: "string", ui: "select", relation: "employee", required: false },
    { key: "shift", label: "Shift", type: "string", ui: "select", relation: "shift", required: false },
    { key: "skill_tags", label: "Skill Tags", type: "string", ui: "multiselect", options: ["CNC","VMC","Lathe","Milling"], required: false },
    { key: "contact_no", label: "Contact No.", type: "string", ui: "text", required: false },
    { key: "email", label: "Email", type: "string", ui: "email", required: false },
    { key: "address", label: "Address", type: "string", ui: "textarea", required: false },
    { key: "aadhar_no", label: "Aadhar No.", type: "string", ui: "text", required: false },
    { key: "pan_no", label: "PAN No.", type: "string", ui: "text", required: false },
    { key: "bank_account_no", label: "Bank Account No.", type: "string", ui: "text", required: false },
    { key: "ifsc_code", label: "IFSC Code", type: "string", ui: "text", required: false },
    { key: "salary_structure", label: "Salary Structure", type: "string", ui: "text", required: false },
    { key: "employment_type", label: "Employment Type", type: "string", ui: "select", options: ["Permanent","Contract","Intern"], required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: false }
  ],
  machine: [
    { key: "machine_id", label: "Machine ID", type: "string", ui: "auto", required: false },
    { key: "machine_name", label: "Machine Name", type: "string", ui: "text", required: false },
    { key: "machine_code", label: "Machine Code", type: "string", ui: "text", required: false },
    { key: "machine_type", label: "Machine Type", type: "string", ui: "select", options: ["CNC","VMC","Lathe","Drill"], required: false },
    { key: "capacity_per_hour", label: "Capacity (Per Hour)", type: "number", ui: "number", required: false },
    { key: "manufacturer", label: "Manufacturer", type: "string", ui: "text", required: false },
    { key: "model_no", label: "Model No.", type: "string", ui: "text", required: false },
    { key: "serial_no", label: "Serial No.", type: "string", ui: "text", required: false },
    { key: "purchase_date", label: "Purchase Date", type: "date", ui: "date", required: false },
    { key: "installation_date", label: "Installation Date", type: "date", ui: "date", required: false },
    { key: "current_location", label: "Current Location", type: "string", ui: "select", relation: "branch", required: false },
    { key: "maintenance_frequency", label: "Maintenance Frequency", type: "string", ui: "select", options: ["Weekly","Monthly","Quarterly"], required: false },
    { key: "last_maintenance_date", label: "Last Maintenance Date", type: "date", ui: "date", required: false },
    { key: "next_due_date", label: "Next Due Date", type: "date", ui: "date", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Running","Idle","Under Maintenance"], required: false },
    { key: "operator_assigned", label: "Operator Assigned", type: "string", ui: "select", relation: "employee", required: false }
  ],
  tool: [
    { key: "tool_id", label: "Tool ID", type: "string", ui: "auto", required: false },
    { key: "tool_name", label: "Tool Name", type: "string", ui: "text", required: false },
    { key: "tool_code", label: "Tool Code", type: "string", ui: "text", required: false },
    { key: "tool_type", label: "Tool Type", type: "string", ui: "select", options: ["Cutting","Measuring","Fixture"], required: false },
    { key: "machine_compatibility", label: "Machine Compatibility", type: "string", ui: "multiselect", options: ["CNC","VMC","Lathe","Drill"], required: false },
    { key: "purchase_date", label: "Purchase Date", type: "date", ui: "date", required: false },
    { key: "tool_life_hours", label: "Tool Life (Hours)", type: "number", ui: "number", required: false },
    { key: "current_usage_hours", label: "Current Usage (Hours)", type: "number", ui: "number", required: false },
    { key: "calibration_date", label: "Calibration Date", type: "date", ui: "date", required: false },
    { key: "next_calibration_due", label: "Next Calibration Due", type: "date", ui: "date", required: false },
    { key: "location", label: "Location", type: "string", ui: "select", relation: "branch", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","In Use","Repair","Scrap"], required: false }
  ],
  shift: [
    { key: "shift_id", label: "Shift ID", type: "string", ui: "auto", required: false },
    { key: "shift_name", label: "Shift Name", type: "string", ui: "text", required: false },
    { key: "shift_code", label: "Shift Code", type: "string", ui: "text", required: false },
    { key: "start_time", label: "Start Time", type: "string", ui: "time", required: false },
    { key: "end_time", label: "End Time", type: "string", ui: "time", required: false },
    { key: "break_duration_minutes", label: "Break Duration (Minutes)", type: "number", ui: "number", required: false },
    { key: "total_hours", label: "Total Hours", type: "string", ui: "computed", required: false },
    { key: "supervisor", label: "Supervisor", type: "string", ui: "select", relation: "employee", required: false },
    { key: "is_default", label: "Is Default", type: "boolean", ui: "checkbox", required: false }
  ],
  currency: [
    { key: "currency_code", label: "Currency Code", type: "string", ui: "text", required: false },
    { key: "currency_name", label: "Currency Name", type: "string", ui: "text", required: false },
    { key: "symbol", label: "Symbol", type: "string", ui: "text", required: false },
    { key: "exchange_rate", label: "Exchange Rate", type: "number", ui: "number", required: false },
    { key: "updated_on", label: "Updated On", type: "date", ui: "date", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_at", label: "Created At", type: "datetime", ui: "datetime", required: false }
  ],
  tax: [
    { key: "tax_id", label: "Tax ID", type: "string", ui: "auto", required: false },
    { key: "tax_name", label: "Tax Name", type: "string", ui: "text", required: false },
    { key: "tax_type", label: "Tax Type", type: "string", ui: "select", options: ["GST","IGST","TDS","VAT"], required: false },
    { key: "tax_rate", label: "Tax Rate (%)", type: "number", ui: "number", required: false },
    { key: "applicable_on", label: "Applicable On", type: "string", ui: "select", options: ["Purchase","Sales","Both"], required: false },
    { key: "hsn_sac", label: "HSN / SAC", type: "string", ui: "text", required: false },
    { key: "effective_from", label: "Effective From", type: "date", ui: "date", required: false },
    { key: "effective_to", label: "Effective To", type: "date", ui: "date", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false }
  ],
  // Inventory & Material Masters
  item: [
    { key: "item_id", label: "Item ID", type: "string", ui: "auto", required: false },
    { key: "item_code", label: "Item Code", type: "string", ui: "text", required: false },
    { key: "item_name", label: "Item Name", type: "string", ui: "text", required: false },
    { key: "item_description", label: "Item Description", type: "string", ui: "textarea", required: false },
    { key: "item_category", label: "Item Category", type: "string", ui: "select", relation: "item_category", required: false },
    { key: "material_type", label: "Material Type", type: "string", ui: "select", relation: "material_type", required: false },
    { key: "uom", label: "UOM (Unit of Measure)", type: "string", ui: "select", options: ["Kg", "Nos", "Meter", "Liter", "Gram", "Ton", "Piece", "Box", "Roll"], required: false },
    { key: "hsn_code", label: "HSN Code", type: "string", ui: "text", required: false },
    { key: "safety_stock", label: "Safety Stock", type: "number", ui: "number", required: false },
    { key: "reorder_level", label: "Reorder Level", type: "number", ui: "number", required: false },
    { key: "reorder_quantity", label: "Reorder Quantity", type: "number", ui: "number", required: false },
    { key: "default_warehouse", label: "Default Warehouse", type: "string", ui: "select", relation: "warehouse", required: false },
    { key: "purchase_rate", label: "Purchase Rate", type: "number", ui: "number", required: false },
    { key: "selling_rate", label: "Selling Rate", type: "number", ui: "number", required: false },
    { key: "valuation_method", label: "Valuation Method", type: "string", ui: "select", options: ["FIFO", "LIFO", "Weighted Avg"], required: false },
    { key: "batch_managed", label: "Batch Managed", type: "boolean", ui: "checkbox", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "created_date", label: "Created Date", type: "datetime", ui: "datetime", required: false }
  ],
  item_category: [
    { key: "category_id", label: "Category ID", type: "string", ui: "auto", required: false },
    { key: "category_name", label: "Category Name", type: "string", ui: "text", required: false },
    { key: "category_code", label: "Category Code", type: "string", ui: "text", required: false },
    { key: "parent_category", label: "Parent Category", type: "string", ui: "select", relation: "item_category", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "created_date", label: "Created Date", type: "datetime", ui: "datetime", required: false }
  ],
  warehouse: [
    { key: "warehouse_id", label: "Warehouse ID", type: "string", ui: "auto", required: false },
    { key: "warehouse_name", label: "Warehouse Name", type: "string", ui: "text", required: false },
    { key: "code", label: "Code", type: "string", ui: "text", required: false },
    { key: "company", label: "Company", type: "string", ui: "select", relation: "company", required: false },
    { key: "address", label: "Address", type: "string", ui: "textarea", required: false },
    { key: "city", label: "City", type: "string", ui: "text", required: false },
    { key: "state", label: "State", type: "string", ui: "text", required: false },
    { key: "country", label: "Country", type: "string", ui: "text", required: false },
    { key: "contact_person", label: "Contact Person", type: "string", ui: "text", required: false },
    { key: "contact_number", label: "Contact Number", type: "string", ui: "text", required: false },
    { key: "capacity", label: "Capacity", type: "number", ui: "number", required: false },
    { key: "temperature_controlled", label: "Temperature Controlled", type: "boolean", ui: "checkbox", required: false },
    { key: "default_warehouse", label: "Default Warehouse", type: "boolean", ui: "checkbox", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  batch: [
    { key: "batch_id", label: "Batch ID", type: "string", ui: "auto", required: false },
    { key: "batch_lot_no", label: "Batch / Lot No", type: "string", ui: "text", required: false },
    { key: "item", label: "Item", type: "string", ui: "select", relation: "item", required: false },
    { key: "quantity", label: "Quantity", type: "number", ui: "number", required: false },
    { key: "uom", label: "UOM", type: "string", ui: "select", options: ["Kg", "Nos", "Meter", "Liter", "Gram", "Ton", "Piece", "Box", "Roll"], required: false },
    { key: "manufacturing_date", label: "Manufacturing Date", type: "date", ui: "date", required: false },
    { key: "expiry_date", label: "Expiry Date", type: "date", ui: "date", required: false },
    { key: "warehouse", label: "Warehouse", type: "string", ui: "select", relation: "warehouse", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Open", "Closed", "Consumed"], required: false },
    { key: "quality_status", label: "Quality Status", type: "string", ui: "select", options: ["Approved", "Rejected", "Hold"], required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  material_type: [
    { key: "material_type_id", label: "Material Type ID", type: "string", ui: "auto", required: false },
    { key: "material_type", label: "Material Type", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  bom: [
    { key: "bom_id", label: "BOM ID", type: "string", ui: "auto", required: false },
    { key: "product", label: "Product", type: "string", ui: "select", relation: "item", required: false },
    { key: "revision_no", label: "Revision No.", type: "string", ui: "text", required: false },
    { key: "effective_from", label: "Effective From", type: "date", ui: "date", required: false },
    { key: "effective_to", label: "Effective To", type: "date", ui: "date", required: false },
    { key: "total_quantity", label: "Total Quantity", type: "number", ui: "number", required: false },
    { key: "uom", label: "UOM", type: "string", ui: "select", options: ["Kg", "Nos", "Meter", "Liter", "Gram", "Ton", "Piece", "Box", "Roll"], required: false },
    { key: "routing", label: "Routing", type: "string", ui: "select", relation: "routing", required: false },
    { key: "scrap_percentage", label: "Scrap %", type: "number", ui: "number", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Obsolete"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "approved_by", label: "Approved By", type: "string", ui: "select", relation: "user", required: false }
  ],
  routing: [
    { key: "routing_id", label: "Routing ID", type: "string", ui: "auto", required: false },
    { key: "routing_name", label: "Routing Name", type: "string", ui: "text", required: false },
    { key: "product", label: "Product", type: "string", ui: "select", relation: "item", required: false },
    { key: "total_operations", label: "Total Operations", type: "number", ui: "computed", required: false },
    { key: "total_estimated_time", label: "Total Estimated Time (hrs)", type: "number", ui: "number", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  material_specification: [
    { key: "specification_id", label: "Specification ID", type: "string", ui: "auto", required: false },
    { key: "item", label: "Item", type: "string", ui: "select", relation: "item", required: false },
    { key: "property_name", label: "Property Name", type: "string", ui: "text", required: false },
    { key: "standard_value", label: "Standard Value", type: "string", ui: "text", required: false },
    { key: "tolerance", label: "Tolerance", type: "string", ui: "text", required: false },
    { key: "unit", label: "Unit", type: "string", ui: "text", required: false },
    { key: "test_method", label: "Test Method", type: "string", ui: "text", required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  // Production & Operations Masters
  work_center: [
    { key: "work_center_id", label: "Work Center ID", type: "string", ui: "auto", required: false },
    { key: "work_center_name", label: "Work Center Name", type: "string", ui: "text", required: false },
    { key: "work_center_code", label: "Work Center Code", type: "string", ui: "text", required: false },
    { key: "department", label: "Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "branch_site", label: "Branch / Site", type: "string", ui: "select", relation: "branch", required: false },
    { key: "machines_assigned", label: "Machines Assigned", type: "string", ui: "multiselect", relation: "machine", required: false },
    { key: "supervisor", label: "Supervisor", type: "string", ui: "select", relation: "employee", required: false },
    { key: "capacity_hours_per_day", label: "Capacity (Hours/Day)", type: "number", ui: "number", required: false },
    { key: "efficiency_percentage", label: "Efficiency (%)", type: "number", ui: "number", required: false },
    { key: "cost_per_hour", label: "Cost per Hour", type: "number", ui: "number", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "created_date", label: "Created Date", type: "datetime", ui: "datetime", required: false }
  ],
  operation: [
    { key: "operation_id", label: "Operation ID", type: "string", ui: "auto", required: false },
    { key: "operation_name", label: "Operation Name", type: "string", ui: "text", required: false },
    { key: "operation_code", label: "Operation Code", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "work_center", label: "Work Center", type: "string", ui: "select", relation: "work_center", required: false },
    { key: "standard_time_minutes", label: "Standard Time (min)", type: "number", ui: "number", required: false },
    { key: "setup_time_minutes", label: "Setup Time (min)", type: "number", ui: "number", required: false },
    { key: "machine_type", label: "Machine Type", type: "string", ui: "select", relation: "machine", required: false },
    { key: "tools_required", label: "Tools Required", type: "string", ui: "multiselect", relation: "tool", required: false },
    { key: "inspection_required", label: "Inspection Required", type: "boolean", ui: "checkbox", required: false },
    { key: "inspection_template", label: "Inspection Template", type: "string", ui: "select", relation: "material_specification", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  process: [
    { key: "process_id", label: "Process ID", type: "string", ui: "auto", required: false },
    { key: "process_name", label: "Process Name", type: "string", ui: "text", required: false },
    { key: "process_code", label: "Process Code", type: "string", ui: "text", required: false },
    { key: "product_type", label: "Product Type", type: "string", ui: "select", relation: "item_category", required: false },
    { key: "version", label: "Version", type: "string", ui: "text", required: false },
    { key: "total_standard_time_minutes", label: "Total Standard Time (min)", type: "number", ui: "computed", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "approved_by", label: "Approved By", type: "string", ui: "select", relation: "user", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Draft", "Active", "Obsolete"], required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false }
  ],
  drawing: [
    { key: "drawing_id", label: "Drawing ID", type: "string", ui: "auto", required: false },
    { key: "drawing_no", label: "Drawing No.", type: "string", ui: "text", required: false },
    { key: "product", label: "Product", type: "string", ui: "select", relation: "item", required: false },
    { key: "revision_no", label: "Revision No.", type: "string", ui: "text", required: false },
    { key: "revision_date", label: "Revision Date", type: "date", ui: "date", required: false },
    { key: "revision_notes", label: "Revision Notes", type: "string", ui: "textarea", required: false },
    { key: "prepared_by", label: "Prepared By", type: "string", ui: "select", relation: "employee", required: false },
    { key: "checked_by", label: "Checked By", type: "string", ui: "select", relation: "employee", required: false },
    { key: "approved_by", label: "Approved By", type: "string", ui: "select", relation: "employee", required: false },
    { key: "file_upload", label: "File Upload", type: "file", ui: "file", required: false },
    { key: "version_control", label: "Version Control", type: "boolean", ui: "checkbox", required: false },
    { key: "linked_bom", label: "Linked BOM", type: "string", ui: "select", relation: "bom", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Obsolete"], required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false }
  ],
  rework_reason: [
    { key: "rework_id", label: "Rework ID", type: "string", ui: "auto", required: false },
    { key: "rework_reason", label: "Rework Reason", type: "string", ui: "text", required: false },
    { key: "category", label: "Category", type: "string", ui: "select", options: ["Dimensional", "Surface", "Assembly"], required: false },
    { key: "department", label: "Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "severity", label: "Severity", type: "string", ui: "select", options: ["Low", "Medium", "High"], required: false },
    { key: "action_plan", label: "Action Plan", type: "string", ui: "textarea", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  downtime_reason: [
    { key: "downtime_id", label: "Downtime ID", type: "string", ui: "auto", required: false },
    { key: "downtime_reason", label: "Downtime Reason", type: "string", ui: "text", required: false },
    { key: "category", label: "Category", type: "string", ui: "select", options: ["Breakdown", "Setup", "Planned", "Material Shortage"], required: false },
    { key: "work_center", label: "Work Center", type: "string", ui: "select", relation: "work_center", required: false },
    { key: "machine", label: "Machine", type: "string", ui: "select", relation: "machine", required: false },
    { key: "expected_duration_minutes", label: "Expected Duration (min)", type: "number", ui: "number", required: false },
    { key: "criticality", label: "Criticality", type: "string", ui: "select", options: ["Low", "Medium", "High"], required: false },
    { key: "department", label: "Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  // Procurement & Vendor Masters
  supplier: [
    { key: "supplier_id", label: "Supplier ID", type: "string", ui: "auto", required: false },
    { key: "supplier_name", label: "Supplier Name", type: "string", ui: "text", required: false },
    { key: "supplier_code", label: "Supplier Code", type: "string", ui: "text", required: false },
    { key: "supplier_type", label: "Supplier Type", type: "string", ui: "select", options: ["Manufacturer", "Dealer", "Service Provider"], required: false },
    { key: "contact_person", label: "Contact Person", type: "string", ui: "text", required: false },
    { key: "contact_number", label: "Contact Number", type: "string", ui: "text", required: false },
    { key: "email", label: "Email", type: "string", ui: "email", required: false },
    { key: "address_line1", label: "Address Line 1", type: "string", ui: "textarea", required: false },
    { key: "address_line2", label: "Address Line 2", type: "string", ui: "textarea", required: false },
    { key: "city", label: "City", type: "string", ui: "text", required: false },
    { key: "state", label: "State", type: "string", ui: "text", required: false },
    { key: "country", label: "Country", type: "string", ui: "text", required: false },
    { key: "pin_code", label: "Pin Code", type: "number", ui: "number", required: false },
    { key: "gstin", label: "GSTIN", type: "string", ui: "text", required: false },
    { key: "pan_no", label: "PAN No", type: "string", ui: "text", required: false },
    { key: "payment_terms", label: "Payment Terms", type: "string", ui: "select", options: ["Net 30", "Net 45", "Advance", "Credit"], required: false },
    { key: "bank_name", label: "Bank Name", type: "string", ui: "text", required: false },
    { key: "account_number", label: "Account Number", type: "string", ui: "text", required: false },
    { key: "ifsc_code", label: "IFSC Code", type: "string", ui: "text", required: false },
    { key: "credit_limit", label: "Credit Limit", type: "number", ui: "number", required: false },
    { key: "lead_time_days", label: "Lead Time (Days)", type: "number", ui: "number", required: false },
    { key: "default_currency", label: "Default Currency", type: "string", ui: "select", options: ["INR", "USD", "EUR"], required: false },
    { key: "supplier_rating", label: "Supplier Rating", type: "string", ui: "select", relation: "supplier_rating", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "created_date", label: "Created Date", type: "datetime", ui: "datetime", required: false }
  ],
  supplier_rating: [
    { key: "rating_id", label: "Rating ID", type: "string", ui: "auto", required: false },
    { key: "rating_name", label: "Rating Name", type: "string", ui: "text", required: false },
    { key: "quality_score_percentage", label: "Quality Score (%)", type: "number", ui: "number", required: false },
    { key: "delivery_score_percentage", label: "Delivery Score (%)", type: "number", ui: "number", required: false },
    { key: "communication_score_percentage", label: "Communication Score (%)", type: "number", ui: "number", required: false },
    { key: "average_score_percentage", label: "Average Score (%)", type: "number", ui: "computed", required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "valid_from", label: "Valid From", type: "date", ui: "date", required: false },
    { key: "valid_to", label: "Valid To", type: "date", ui: "date", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  purchase_type: [
    { key: "purchase_type_id", label: "Purchase Type ID", type: "string", ui: "auto", required: false },
    { key: "purchase_type", label: "Purchase Type", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "tax_applicability", label: "Tax Applicability", type: "string", ui: "select", options: ["GST", "IGST", "Import Duty"], required: false },
    { key: "currency", label: "Currency", type: "string", ui: "select", options: ["INR", "USD", "EUR"], required: false },
    { key: "payment_terms", label: "Payment Terms", type: "string", ui: "select", options: ["Net 30", "Net 45", "Advance", "Credit"], required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  lead_time: [
    { key: "lead_time_id", label: "Lead Time ID", type: "string", ui: "auto", required: false },
    { key: "supplier", label: "Supplier", type: "string", ui: "select", relation: "supplier", required: false },
    { key: "item", label: "Item", type: "string", ui: "select", relation: "item", required: false },
    { key: "lead_time_days", label: "Lead Time (Days)", type: "number", ui: "number", required: false },
    { key: "minimum_order_quantity", label: "Minimum Order Quantity", type: "number", ui: "number", required: false },
    { key: "effective_from", label: "Effective From", type: "date", ui: "date", required: false },
    { key: "effective_to", label: "Effective To", type: "date", ui: "date", required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  subcontractor: [
    { key: "subcontractor_id", label: "Subcontractor ID", type: "string", ui: "auto", required: false },
    { key: "subcontractor_name", label: "Subcontractor Name", type: "string", ui: "text", required: false },
    { key: "subcontractor_code", label: "Subcontractor Code", type: "string", ui: "text", required: false },
    { key: "contact_person", label: "Contact Person", type: "string", ui: "text", required: false },
    { key: "contact_number", label: "Contact Number", type: "string", ui: "text", required: false },
    { key: "email", label: "Email", type: "string", ui: "email", required: false },
    { key: "address", label: "Address", type: "string", ui: "textarea", required: false },
    { key: "city", label: "City", type: "string", ui: "text", required: false },
    { key: "state", label: "State", type: "string", ui: "text", required: false },
    { key: "country", label: "Country", type: "string", ui: "text", required: false },
    { key: "gstin", label: "GSTIN", type: "string", ui: "text", required: false },
    { key: "pan_no", label: "PAN No", type: "string", ui: "text", required: false },
    { key: "linked_operations", label: "Linked Operations", type: "string", ui: "multiselect", relation: "operation", required: false },
    { key: "service_type", label: "Service Type", type: "string", ui: "select", options: ["Processing", "Fabrication", "Assembly"], required: false },
    { key: "payment_terms", label: "Payment Terms", type: "string", ui: "select", options: ["Net 30", "Advance"], required: false },
    { key: "lead_time_days", label: "Lead Time (Days)", type: "number", ui: "number", required: false },
    { key: "rating", label: "Rating", type: "string", ui: "select", relation: "supplier_rating", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  // Sales & Customer Masters
  customer: [
    { key: "customer_id", label: "Customer ID", type: "string", ui: "auto", required: false },
    { key: "customer_name", label: "Customer Name", type: "string", ui: "text", required: false },
    { key: "customer_code", label: "Customer Code", type: "string", ui: "text", required: false },
    { key: "customer_type", label: "Customer Type", type: "string", ui: "select", relation: "customer_type", required: false },
    { key: "contact_person", label: "Contact Person", type: "string", ui: "text", required: false },
    { key: "contact_number", label: "Contact Number", type: "string", ui: "text", required: false },
    { key: "email", label: "Email", type: "string", ui: "email", required: false },
    { key: "address_line1", label: "Address Line 1", type: "string", ui: "textarea", required: false },
    { key: "address_line2", label: "Address Line 2", type: "string", ui: "textarea", required: false },
    { key: "city", label: "City", type: "string", ui: "text", required: false },
    { key: "state", label: "State", type: "string", ui: "text", required: false },
    { key: "country", label: "Country", type: "string", ui: "text", required: false },
    { key: "pin_code", label: "Pin Code", type: "number", ui: "number", required: false },
    { key: "gstin", label: "GSTIN", type: "string", ui: "text", required: false },
    { key: "pan_no", label: "PAN No", type: "string", ui: "text", required: false },
    { key: "payment_terms", label: "Payment Terms", type: "string", ui: "select", options: ["Net 30", "Advance", "Credit"], required: false },
    { key: "credit_limit", label: "Credit Limit", type: "number", ui: "number", required: false },
    { key: "outstanding_balance", label: "Outstanding Balance", type: "number", ui: "number", required: false },
    { key: "default_currency", label: "Default Currency", type: "string", ui: "select", options: ["INR", "USD", "EUR"], required: false },
    { key: "category", label: "Category", type: "string", ui: "select", options: ["OEM", "Retail", "Export"], required: false },
    { key: "price_list", label: "Price List", type: "string", ui: "select", relation: "price_list", required: false },
    { key: "transporter", label: "Transporter", type: "string", ui: "select", relation: "transporter", required: false },
    { key: "dispatch_location", label: "Dispatch Location", type: "string", ui: "select", relation: "dispatch_location", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "created_date", label: "Created Date", type: "datetime", ui: "datetime", required: false }
  ],
  // Customer Masters (simple: name + status)
  customer_type: [
    { key: "name", label: "Name", type: "string", ui: "text", required: true },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: true }
  ],
  industry: [
    { key: "name", label: "Name", type: "string", ui: "text", required: true },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: true }
  ],
  territory: [
    { key: "name", label: "Name", type: "string", ui: "text", required: true },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: true }
  ],
  market_segment: [
    { key: "name", label: "Name", type: "string", ui: "text", required: true },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: true }
  ],
  status_master: [
    { key: "name", label: "Name", type: "string", ui: "text", required: true },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: true }
  ],
  state_master: [
    { key: "name", label: "Name", type: "string", ui: "text", required: true },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: true }
  ],
  salutation: [
    { key: "name", label: "Name", type: "string", ui: "text", required: true },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: true }
  ],
  price_list: [
    { key: "price_list_id", label: "Price List ID", type: "string", ui: "auto", required: false },
    { key: "price_list_name", label: "Price List Name", type: "string", ui: "text", required: false },
    { key: "valid_from", label: "Valid From", type: "date", ui: "date", required: false },
    { key: "valid_to", label: "Valid To", type: "date", ui: "date", required: false },
    { key: "currency", label: "Currency", type: "string", ui: "select", options: ["INR", "USD", "EUR"], required: false },
    { key: "customer_type", label: "Customer Type", type: "string", ui: "select", relation: "customer_type", required: false },
    { key: "tax_type", label: "Tax Type", type: "string", ui: "select", options: ["GST", "IGST", "VAT"], required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  dispatch_location: [
    { key: "dispatch_id", label: "Dispatch ID", type: "string", ui: "auto", required: false },
    { key: "customer", label: "Customer", type: "string", ui: "select", relation: "customer", required: false },
    { key: "location_name", label: "Location Name", type: "string", ui: "text", required: false },
    { key: "address_line1", label: "Address Line 1", type: "string", ui: "textarea", required: false },
    { key: "address_line2", label: "Address Line 2", type: "string", ui: "textarea", required: false },
    { key: "city", label: "City", type: "string", ui: "text", required: false },
    { key: "state", label: "State", type: "string", ui: "text", required: false },
    { key: "country", label: "Country", type: "string", ui: "text", required: false },
    { key: "pin_code", label: "Pin Code", type: "number", ui: "number", required: false },
    { key: "contact_person", label: "Contact Person", type: "string", ui: "text", required: false },
    { key: "contact_number", label: "Contact Number", type: "string", ui: "text", required: false },
    { key: "transporter", label: "Transporter", type: "string", ui: "select", relation: "transporter", required: false },
    { key: "gstin", label: "GSTIN", type: "string", ui: "text", required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  transporter: [
    { key: "transporter_id", label: "Transporter ID", type: "string", ui: "auto", required: false },
    { key: "transporter_name", label: "Transporter Name", type: "string", ui: "text", required: false },
    { key: "code", label: "Code", type: "string", ui: "text", required: false },
    { key: "contact_person", label: "Contact Person", type: "string", ui: "text", required: false },
    { key: "contact_number", label: "Contact Number", type: "string", ui: "text", required: false },
    { key: "email", label: "Email", type: "string", ui: "email", required: false },
    { key: "address", label: "Address", type: "string", ui: "textarea", required: false },
    { key: "city", label: "City", type: "string", ui: "text", required: false },
    { key: "state", label: "State", type: "string", ui: "text", required: false },
    { key: "country", label: "Country", type: "string", ui: "text", required: false },
    { key: "gstin", label: "GSTIN", type: "string", ui: "text", required: false },
    { key: "vehicle_capacity", label: "Vehicle Capacity", type: "string", ui: "text", required: false },
    { key: "service_type", label: "Service Type", type: "string", ui: "select", options: ["Local", "National", "International"], required: false },
    { key: "rating", label: "Rating", type: "number", ui: "number", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  credit_limit: [
    { key: "credit_limit_id", label: "Credit Limit ID", type: "string", ui: "auto", required: false },
    { key: "customer", label: "Customer", type: "string", ui: "select", relation: "customer", required: false },
    { key: "credit_limit", label: "Credit Limit", type: "number", ui: "number", required: false },
    { key: "credit_days", label: "Credit Days", type: "number", ui: "number", required: false },
    { key: "current_outstanding", label: "Current Outstanding", type: "number", ui: "number", required: false },
    { key: "credit_risk_category", label: "Credit Risk Category", type: "string", ui: "select", options: ["Low", "Medium", "High"], required: false },
    { key: "last_review_date", label: "Last Review Date", type: "date", ui: "date", required: false },
    { key: "next_review_date", label: "Next Review Date", type: "date", ui: "date", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Hold", "Suspended"], required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  // Quality & Maintenance Masters
  qc_parameter: [
    { key: "qc_parameter_id", label: "QC Parameter ID", type: "string", ui: "auto", required: false },
    { key: "parameter_name", label: "Parameter Name", type: "string", ui: "text", required: false },
    { key: "parameter_code", label: "Parameter Code", type: "string", ui: "text", required: false },
    { key: "item", label: "Item", type: "string", ui: "select", relation: "item", required: false },
    { key: "specification", label: "Specification", type: "string", ui: "text", required: false },
    { key: "tolerance", label: "Tolerance", type: "string", ui: "text", required: false },
    { key: "uom", label: "UOM", type: "string", ui: "text", required: false },
    { key: "test_method", label: "Test Method", type: "string", ui: "text", required: false },
    { key: "equipment", label: "Equipment", type: "string", ui: "text", required: false },
    { key: "frequency", label: "Frequency", type: "string", ui: "select", options: ["Each Batch", "Each Piece", "Random"], required: false },
    { key: "sampling_plan", label: "Sampling Plan", type: "string", ui: "select", relation: "sampling_plan", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "created_date", label: "Created Date", type: "datetime", ui: "datetime", required: false }
  ],
  sampling_plan: [
    { key: "sampling_plan_id", label: "Sampling Plan ID", type: "string", ui: "auto", required: false },
    { key: "sampling_plan_name", label: "Sampling Plan Name", type: "string", ui: "text", required: false },
    { key: "sampling_type", label: "Sampling Type", type: "string", ui: "select", options: ["Random", "100%", "AQL"], required: false },
    { key: "sample_quantity_percentage", label: "Sample Quantity (%)", type: "number", ui: "number", required: false },
    { key: "criteria", label: "Criteria", type: "string", ui: "textarea", required: false },
    { key: "applicable_for", label: "Applicable For", type: "string", ui: "select", options: ["Incoming", "In-Process", "Final"], required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  inspection_template: [
    { key: "template_id", label: "Template ID", type: "string", ui: "auto", required: false },
    { key: "template_name", label: "Template Name", type: "string", ui: "text", required: false },
    { key: "linked_item", label: "Linked Item", type: "string", ui: "select", relation: "item", required: false },
    { key: "inspection_type", label: "Inspection Type", type: "string", ui: "select", options: ["Incoming", "In-Process", "Final"], required: false },
    { key: "sampling_plan", label: "Sampling Plan", type: "string", ui: "select", relation: "sampling_plan", required: false },
    { key: "approval_required", label: "Approval Required", type: "boolean", ui: "checkbox", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  rejection_code: [
    { key: "rejection_code_id", label: "Rejection Code ID", type: "string", ui: "auto", required: false },
    { key: "rejection_code", label: "Rejection Code", type: "string", ui: "text", required: false },
    { key: "rejection_reason", label: "Rejection Reason", type: "string", ui: "text", required: false },
    { key: "category", label: "Category", type: "string", ui: "select", options: ["Dimensional", "Surface", "Functional"], required: false },
    { key: "severity", label: "Severity", type: "string", ui: "select", options: ["Low", "Medium", "High"], required: false },
    { key: "action_type", label: "Action Type", type: "string", ui: "select", options: ["Rework", "Scrap", "Accept under deviation"], required: false },
    { key: "department", label: "Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false },
    { key: "created_date", label: "Created Date", type: "datetime", ui: "datetime", required: false }
  ],
  ncr_type: [
    { key: "ncr_type_id", label: "NCR Type ID", type: "string", ui: "auto", required: false },
    { key: "ncr_type_name", label: "NCR Type Name", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "source", label: "Source", type: "string", ui: "select", options: ["Supplier", "In-Process", "Customer"], required: false },
    { key: "severity", label: "Severity", type: "string", ui: "select", options: ["Low", "Medium", "High"], required: false },
    { key: "responsible_department", label: "Responsible Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "corrective_action_required", label: "Corrective Action Required", type: "boolean", ui: "checkbox", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  maintenance_schedule: [
    { key: "schedule_id", label: "Schedule ID", type: "string", ui: "auto", required: false },
    { key: "machine", label: "Machine", type: "string", ui: "select", relation: "machine", required: false },
    { key: "maintenance_type", label: "Maintenance Type", type: "string", ui: "select", options: ["Preventive", "Predictive", "Breakdown"], required: false },
    { key: "frequency", label: "Frequency", type: "string", ui: "select", options: ["Daily", "Weekly", "Monthly", "Quarterly", "Yearly"], required: false },
    { key: "last_maintenance_date", label: "Last Maintenance Date", type: "date", ui: "date", required: false },
    { key: "next_due_date", label: "Next Due Date", type: "date", ui: "date", required: false },
    { key: "responsible_person", label: "Responsible Person", type: "string", ui: "select", relation: "employee", required: false },
    { key: "checklist_template", label: "Checklist Template", type: "string", ui: "text", required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Completed", "Pending"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  tool_life: [
    { key: "tool_life_id", label: "Tool Life ID", type: "string", ui: "auto", required: false },
    { key: "tool", label: "Tool", type: "string", ui: "select", relation: "tool", required: false },
    { key: "machine", label: "Machine", type: "string", ui: "select", relation: "machine", required: false },
    { key: "operator", label: "Operator", type: "string", ui: "select", relation: "employee", required: false },
    { key: "total_tool_life_hours", label: "Total Tool Life (Hours)", type: "number", ui: "number", required: false },
    { key: "used_hours", label: "Used Hours", type: "number", ui: "number", required: false },
    { key: "remaining_life", label: "Remaining Life", type: "number", ui: "computed", required: false },
    { key: "last_calibration_date", label: "Last Calibration Date", type: "date", ui: "date", required: false },
    { key: "next_calibration_due", label: "Next Calibration Due", type: "date", ui: "date", required: false },
    { key: "calibration_status", label: "Calibration Status", type: "string", ui: "select", options: ["Pending", "Done", "Overdue"], required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  // HR & Payroll Masters
  designation: [
    { key: "name", label: "Name", type: "string", ui: "text", required: true },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active","Inactive"], required: true }
  ],
  grade: [
    { key: "grade_id", label: "Grade ID", type: "string", ui: "auto", required: false },
    { key: "grade_name", label: "Grade Name", type: "string", ui: "text", required: false },
    { key: "grade_code", label: "Grade Code", type: "string", ui: "text", required: false },
    { key: "minimum_salary", label: "Minimum Salary", type: "number", ui: "number", required: false },
    { key: "maximum_salary", label: "Maximum Salary", type: "number", ui: "number", required: false },
    { key: "increment_percentage", label: "Increment %", type: "number", ui: "number", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  leave_type: [
    { key: "leave_type_id", label: "Leave Type ID", type: "string", ui: "auto", required: false },
    { key: "leave_type_name", label: "Leave Type Name", type: "string", ui: "text", required: false },
    { key: "leave_code", label: "Leave Code", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "annual_quota_days", label: "Annual Quota (Days)", type: "number", ui: "number", required: false },
    { key: "carry_forward", label: "Carry Forward", type: "boolean", ui: "checkbox", required: false },
    { key: "encashable", label: "Encashable", type: "boolean", ui: "checkbox", required: false },
    { key: "paid_leave", label: "Paid Leave", type: "boolean", ui: "checkbox", required: false },
    { key: "applicable_to", label: "Applicable To", type: "string", ui: "select", options: ["Permanent", "Contract", "All"], required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  skill_matrix: [
    { key: "skill_matrix_id", label: "Skill Matrix ID", type: "string", ui: "auto", required: false },
    { key: "employee", label: "Employee", type: "string", ui: "select", relation: "employee", required: false },
    { key: "machine", label: "Machine", type: "string", ui: "select", relation: "machine", required: false },
    { key: "skill_level", label: "Skill Level", type: "string", ui: "select", options: ["Beginner", "Intermediate", "Expert"], required: false },
    { key: "certification", label: "Certification", type: "string", ui: "text", required: false },
    { key: "valid_from", label: "Valid From", type: "date", ui: "date", required: false },
    { key: "valid_to", label: "Valid To", type: "date", ui: "date", required: false },
    { key: "verified_by", label: "Verified By", type: "string", ui: "select", relation: "user", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Expired"], required: false },
    { key: "remarks", label: "Remarks", type: "string", ui: "textarea", required: false },
    { key: "created_date", label: "Created Date", type: "datetime", ui: "datetime", required: false }
  ],
  salary_structure: [
    { key: "structure_id", label: "Structure ID", type: "string", ui: "auto", required: false },
    { key: "structure_name", label: "Structure Name", type: "string", ui: "text", required: false },
    { key: "grade", label: "Grade", type: "string", ui: "select", relation: "grade", required: false },
    { key: "basic_percentage", label: "Basic (%)", type: "number", ui: "number", required: false },
    { key: "hra_percentage", label: "HRA (%)", type: "number", ui: "number", required: false },
    { key: "calculation_formula", label: "Calculation Formula", type: "string", ui: "textarea", required: false },
    { key: "effective_from", label: "Effective From", type: "date", ui: "date", required: false },
    { key: "effective_to", label: "Effective To", type: "date", ui: "date", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  holiday_list: [
    { key: "holiday_list_id", label: "Holiday List ID", type: "string", ui: "auto", required: false },
    { key: "holiday_name", label: "Holiday Name", type: "string", ui: "text", required: false },
    { key: "date", label: "Date", type: "date", ui: "date", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "location", label: "Location", type: "string", ui: "select", relation: "branch", required: false },
    { key: "region", label: "Region", type: "string", ui: "text", required: false },
    { key: "recurring", label: "Recurring", type: "boolean", ui: "checkbox", required: false },
    { key: "category", label: "Category", type: "string", ui: "select", options: ["National", "Festival", "Optional"], required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  // Finance & Accounting Masters
  chart_of_accounts: [
    { key: "account_id", label: "Account ID", type: "string", ui: "auto", required: false },
    { key: "account_name", label: "Account Name", type: "string", ui: "text", required: false },
    { key: "account_code", label: "Account Code", type: "string", ui: "text", required: false },
    { key: "account_type", label: "Account Type", type: "string", ui: "select", options: ["Asset", "Liability", "Income", "Expense"], required: false },
    { key: "parent_account", label: "Parent Account", type: "string", ui: "select", relation: "chart_of_accounts", required: false },
    { key: "level", label: "Level", type: "number", ui: "number", required: false },
    { key: "is_group", label: "Is Group", type: "boolean", ui: "checkbox", required: false },
    { key: "opening_balance", label: "Opening Balance", type: "number", ui: "number", required: false },
    { key: "currency", label: "Currency", type: "string", ui: "select", options: ["INR", "USD", "EUR"], required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  cost_center: [
    { key: "cost_center_id", label: "Cost Center ID", type: "string", ui: "auto", required: false },
    { key: "cost_center_name", label: "Cost Center Name", type: "string", ui: "text", required: false },
    { key: "cost_center_code", label: "Cost Center Code", type: "string", ui: "text", required: false },
    { key: "linked_department", label: "Linked Department", type: "string", ui: "select", relation: "department", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  bank_account: [
    { key: "bank_account_id", label: "Bank Account ID", type: "string", ui: "auto", required: false },
    { key: "bank_name", label: "Bank Name", type: "string", ui: "text", required: false },
    { key: "branch_name", label: "Branch Name", type: "string", ui: "text", required: false },
    { key: "account_holder_name", label: "Account Holder Name", type: "string", ui: "text", required: false },
    { key: "account_number", label: "Account Number", type: "string", ui: "text", required: false },
    { key: "ifsc_code", label: "IFSC Code", type: "string", ui: "text", required: false },
    { key: "account_type", label: "Account Type", type: "string", ui: "select", options: ["Current", "Savings"], required: false },
    { key: "linked_company", label: "Linked Company", type: "string", ui: "select", relation: "company", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  payment_terms: [
    { key: "payment_term_id", label: "Payment Term ID", type: "string", ui: "auto", required: false },
    { key: "term_name", label: "Term Name", type: "string", ui: "text", required: false },
    { key: "term_code", label: "Term Code", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "due_days", label: "Due Days", type: "number", ui: "number", required: false },
    { key: "discount_percentage", label: "Discount (%)", type: "number", ui: "number", required: false },
    { key: "applicable_for", label: "Applicable For", type: "string", ui: "select", options: ["Customer", "Supplier", "Both"], required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  tax_type: [
    { key: "tax_type_id", label: "Tax Type ID", type: "string", ui: "auto", required: false },
    { key: "tax_type_name", label: "Tax Type Name", type: "string", ui: "text", required: false },
    { key: "tax_type_code", label: "Tax Type Code", type: "string", ui: "text", required: false },
    { key: "tax_rate_percentage", label: "Tax Rate (%)", type: "number", ui: "number", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "effective_from", label: "Effective From", type: "date", ui: "date", required: false },
    { key: "effective_to", label: "Effective To", type: "date", ui: "date", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  tax_master: [
    { key: "tax_id", label: "Tax ID", type: "string", ui: "auto", required: false },
    { key: "tax_name", label: "Tax Name", type: "string", ui: "text", required: false },
    { key: "tax_type", label: "Tax Type", type: "string", ui: "select", relation: "tax_type", required: false },
    { key: "applicable_on", label: "Applicable On", type: "string", ui: "select", options: ["Purchase", "Sales", "Both"], required: false },
    { key: "hsn_sac_code", label: "HSN / SAC Code", type: "string", ui: "text", required: false },
    { key: "effective_from", label: "Effective From", type: "date", ui: "date", required: false },
    { key: "effective_to", label: "Effective To", type: "date", ui: "date", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  ledger_master: [
    { key: "ledger_id", label: "Ledger ID", type: "string", ui: "auto", required: false },
    { key: "ledger_name", label: "Ledger Name", type: "string", ui: "text", required: false },
    { key: "ledger_code", label: "Ledger Code", type: "string", ui: "text", required: false },
    { key: "under_account", label: "Under Account", type: "string", ui: "select", relation: "chart_of_accounts", required: false },
    { key: "linked_party", label: "Linked Party", type: "string", ui: "text", required: false },
    { key: "opening_balance", label: "Opening Balance", type: "number", ui: "number", required: false },
    { key: "dr_cr", label: "Dr/Cr", type: "string", ui: "select", options: ["Debit", "Credit"], required: false },
    { key: "is_tally_synced", label: "Is Tally Synced", type: "boolean", ui: "checkbox", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  expense_type: [
    { key: "expense_type_id", label: "Expense Type ID", type: "string", ui: "auto", required: false },
    { key: "expense_type_name", label: "Expense Type Name", type: "string", ui: "text", required: false },
    { key: "expense_code", label: "Expense Code", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "linked_cost_center", label: "Linked Cost Center", type: "string", ui: "select", relation: "cost_center", required: false },
    { key: "reimbursable", label: "Reimbursable", type: "boolean", ui: "checkbox", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  // Configuration & Utility Masters
  approval_workflow: [
    { key: "workflow_id", label: "Workflow ID", type: "string", ui: "auto", required: false },
    { key: "workflow_name", label: "Workflow Name", type: "string", ui: "text", required: false },
    { key: "document_type", label: "Document Type", type: "string", ui: "select", options: ["PO", "NCR", "BOM", "Invoice"], required: false },
    { key: "levels", label: "Levels", type: "number", ui: "number", required: false },
    { key: "level_details", label: "Level Details", type: "string", ui: "textarea", required: false },
    { key: "effective_from", label: "Effective From", type: "date", ui: "date", required: false },
    { key: "effective_to", label: "Effective To", type: "date", ui: "date", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  notification_alert: [
    { key: "notification_id", label: "Notification ID", type: "string", ui: "auto", required: false },
    { key: "notification_name", label: "Notification Name", type: "string", ui: "text", required: false },
    { key: "trigger_event", label: "Trigger Event", type: "string", ui: "text", required: false },
    { key: "delivery_channel", label: "Delivery Channel", type: "string", ui: "multiselect", options: ["Email", "SMS", "In-App"], required: false },
    { key: "recipient_role", label: "Recipient Role", type: "string", ui: "select", relation: "role", required: false },
    { key: "message_template", label: "Message Template", type: "string", ui: "textarea", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  document_type: [
    { key: "document_type_id", label: "Document Type ID", type: "string", ui: "auto", required: false },
    { key: "document_name", label: "Document Name", type: "string", ui: "text", required: false },
    { key: "prefix", label: "Prefix", type: "string", ui: "text", required: false },
    { key: "suffix", label: "Suffix", type: "string", ui: "text", required: false },
    { key: "running_number", label: "Running Number", type: "number", ui: "number", required: false },
    { key: "padding", label: "Padding", type: "number", ui: "number", required: false },
    { key: "format_preview", label: "Format Preview", type: "string", ui: "computed", required: false },
    { key: "reset_frequency", label: "Reset Frequency", type: "string", ui: "select", options: ["Yearly", "Monthly", "Never"], required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  barcode_qr_setup: [
    { key: "setup_id", label: "Setup ID", type: "string", ui: "auto", required: false },
    { key: "label_type", label: "Label Type", type: "string", ui: "select", options: ["Barcode", "QR Code"], required: false },
    { key: "linked_module", label: "Linked Module", type: "string", ui: "select", options: ["Item", "Batch", "Dispatch", "Employee"], required: false },
    { key: "label_format", label: "Label Format", type: "string", ui: "text", required: false },
    { key: "print_size", label: "Print Size", type: "string", ui: "text", required: false },
    { key: "active", label: "Active", type: "boolean", ui: "checkbox", required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  integration_master: [
    { key: "integration_id", label: "Integration ID", type: "string", ui: "auto", required: false },
    { key: "integration_name", label: "Integration Name", type: "string", ui: "text", required: false },
    { key: "module_linked", label: "Module Linked", type: "string", ui: "select", options: ["HR", "Finance", "Inventory", "All"], required: false },
    { key: "api_endpoint", label: "API Endpoint", type: "string", ui: "url", required: false },
    { key: "auth_type", label: "Auth Type", type: "string", ui: "select", options: ["API Key", "OAuth2", "None"], required: false },
    { key: "auth_token", label: "Auth Token", type: "string", ui: "password", required: false },
    { key: "last_sync_date", label: "Last Sync Date", type: "datetime", ui: "datetime", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ],
  job_card_template: [
    { key: "template_id", label: "Template ID", type: "string", ui: "auto", required: false },
    { key: "template_name", label: "Template Name", type: "string", ui: "text", required: true },
    { key: "template_code", label: "Template Code", type: "string", ui: "text", required: false },
    { key: "description", label: "Description", type: "string", ui: "textarea", required: false },
    { key: "operations", label: "Operations", type: "string", ui: "operations_table", required: false },
    { key: "status", label: "Status", type: "string", ui: "select", options: ["Active", "Inactive"], required: false },
    { key: "created_by", label: "Created By", type: "string", ui: "select", relation: "user", required: false }
  ]
}

export const masterLabels: Record<string, string> = {
  company: "Company",
  branch: "Branch / Site",
  department: "Department", 
  user: "User",
  role: "Role",
  employee: "Employee",
  machine: "Machine",
  tool: "Tool & Fixture",
  shift: "Shift",
  currency: "Currency",
  tax: "Tax",
  // Inventory & Material Masters
  item: "Item Master",
  item_category: "Item Category Master",
  warehouse: "Warehouse Master",
  batch: "Batch Master",
  material_type: "Material Type Master",
  bom: "BOM Master",
  routing: "Routing Master",
  material_specification: "Material Specification Master",
  // Production & Operations Masters
  work_center: "Work Center Master",
  operation: "Operation Master",
  process: "Process Master",
  drawing: "Drawing Master",
  rework_reason: "Rework Reason Master",
  downtime_reason: "Downtime Reason Master",
  // Procurement & Vendor Masters
  supplier: "Supplier Master",
  supplier_rating: "Supplier Rating Master",
  purchase_type: "Purchase Type Master",
  lead_time: "Lead Time Master",
  subcontractor: "Subcontractor Master",
  // Sales & Customer Masters
  customer: "Customer Master",
  customer_type: "Customer Type Master",
  industry: "Industry Master",
  territory: "Territory Master",
  market_segment: "Market Segment Master",
  status_master: "Status Master",
  state_master: "State Master",
  salutation: "Salutation Master",
  price_list: "Price List Master",
  dispatch_location: "Dispatch Location Master",
  transporter: "Transporter Master",
  credit_limit: "Credit Limit Master",
  // Quality & Maintenance Masters
  qc_parameter: "QC Parameter Master",
  sampling_plan: "Sampling Plan Master",
  inspection_template: "Inspection Template Master",
  rejection_code: "Rejection Code Master",
  ncr_type: "NCR Type Master",
  maintenance_schedule: "Maintenance Schedule Master",
  tool_life: "Tool Life Master",
  // HR & Payroll Masters
  designation: "Designation Master",
  grade: "Grade / Level Master",
  leave_type: "Leave Type Master",
  skill_matrix: "Skill Matrix Master",
  salary_structure: "Salary Structure Master",
  holiday_list: "Holiday List Master",
  // Finance & Accounting Masters
  chart_of_accounts: "Chart of Accounts Master",
  cost_center: "Cost Center Master",
  bank_account: "Bank Account Master",
  payment_terms: "Payment Terms Master",
  tax_type: "Tax Type Master",
  tax_master: "Tax Master",
  ledger_master: "Ledger Master",
  expense_type: "Expense Type Master",
  // Configuration & Utility Masters
  approval_workflow: "Approval Workflow Master",
  notification_alert: "Notification & Alert Master",
  document_type: "Document Type Master",
  barcode_qr_setup: "Barcode / QR Setup Master",
  integration_master: "Integration Master",
  job_card_template: "Job Card Template Master"
}

// ID field mapping for each master
export const masterIdFields: Record<string, string> = {
  company: 'company_id',
  branch: 'branch_id',
  department: 'department_id',
  user: 'user_id',
  role: 'role_id',
  employee: 'employee_id',
  machine: 'machine_id',
  tool: 'tool_id',
  shift: 'shift_id',
  currency: 'currency_code',
  tax: 'tax_id',
  // Inventory & Material Masters
  item: 'item_id',
  item_category: 'category_id',
  warehouse: 'warehouse_id',
  batch: 'batch_id',
  material_type: 'material_type_id',
  bom: 'bom_id',
  routing: 'routing_id',
  material_specification: 'specification_id',
  // Production & Operations Masters
  work_center: 'work_center_id',
  operation: 'operation_id',
  process: 'process_id',
  drawing: 'drawing_id',
  rework_reason: 'rework_id',
  downtime_reason: 'downtime_id',
  // Procurement & Vendor Masters
  supplier: 'supplier_id',
  supplier_rating: 'rating_id',
  purchase_type: 'purchase_type_id',
  lead_time: 'lead_time_id',
  subcontractor: 'subcontractor_id',
  // Sales & Customer Masters
  customer: 'customer_id',
  customer_type: 'customer_type_id',
  industry: 'industry_id',
  territory: 'territory_id',
  market_segment: 'market_segment_id',
  status_master: 'status_id',
  state_master: 'state_id',
  salutation: 'salutation_id',
  price_list: 'price_list_id',
  dispatch_location: 'dispatch_id',
  transporter: 'transporter_id',
  credit_limit: 'credit_limit_id',
  // Quality & Maintenance Masters
  qc_parameter: 'qc_parameter_id',
  sampling_plan: 'sampling_plan_id',
  inspection_template: 'template_id',
  rejection_code: 'rejection_code_id',
  ncr_type: 'ncr_type_id',
  maintenance_schedule: 'schedule_id',
  tool_life: 'tool_life_id',
  // HR & Payroll Masters
  designation: 'designation_id',
  grade: 'grade_id',
  leave_type: 'leave_type_id',
  skill_matrix: 'skill_matrix_id',
  salary_structure: 'structure_id',
  holiday_list: 'holiday_list_id',
  // Finance & Accounting Masters
  chart_of_accounts: 'account_id',
  cost_center: 'cost_center_id',
  bank_account: 'bank_account_id',
  payment_terms: 'payment_term_id',
  tax_type: 'tax_type_id',
  ledger_master: 'ledger_id',
  expense_type: 'expense_type_id',
  // Configuration & Utility Masters
  approval_workflow: 'workflow_id',
  notification_alert: 'notification_id',
  document_type: 'document_type_id',
  barcode_qr_setup: 'setup_id',
  integration_master: 'integration_id',
  job_card_template: 'template_id'
}

// Helper function to get the ID field for a master
export const getMasterIdField = (masterKey: string): string => {
  return masterIdFields[masterKey] || `${masterKey}_id`
}
